In [1]:
# Import dependencies
import pandas as pd
from pathlib import Path

In [2]:
# Create a list of file paths
file_paths = [
    'citibike_data/JC-202201-citibike-tripdata.csv',
    'citibike_data/JC-202202-citibike-tripdata.csv',
    'citibike_data/JC-202203-citibike-tripdata.csv',
    'citibike_data/JC-202204-citibike-tripdata.csv',
    'citibike_data/JC-202205-citibike-tripdata.csv',
    'citibike_data/JC-202206-citibike-tripdata.csv',
    'citibike_data/JC-202207-citbike-tripdata.csv',
    'citibike_data/JC-202208-citibike-tripdata.csv',
    'citibike_data/JC-202209-citibike-tripdata.csv',
    'citibike_data/JC-202210-citibike-tripdata.csv',
    'citibike_data/JC-202211-citibike-tripdata.csv',
    'citibike_data/JC-202212-citibike-tripdata.csv',
]

In [3]:
# Read all CSV files into a list of DataFrames
dfs = [pd.read_csv(file) for file in file_paths]

In [4]:
# Concatenate all DataFrames into one
combined_df = pd.concat(dfs, ignore_index=True)

In [9]:
combined_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,CA5837152804D4B5,electric_bike,2022-01-26 18:50:39,2022-01-26 18:51:53,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
1,BA06A5E45B6601D2,classic_bike,2022-01-28 13:14:07,2022-01-28 13:20:23,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
2,7B6827D7B9508D93,classic_bike,2022-01-10 19:55:13,2022-01-10 20:00:37,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
3,6E5864EA6FCEC90D,electric_bike,2022-01-26 07:54:57,2022-01-26 07:55:22,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
4,E24954255BBDE32D,electric_bike,2022-01-13 18:44:46,2022-01-13 18:45:43,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member

In [6]:
# Drop rows with null values
combined_df = combined_df.dropna()

In [ ]:
# Write to a new CSV file
combined_df.to_csv('citibike_data/combined_citibike_data.csv', index=False)